name: my-workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: make lint
      - uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with: 
          coverageCommand: make test-coverage
          debug: true